// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "*.onnx" {
  /**
   * A path to the ONNX model file for use in onnxruntime-web
   */
  const path: `${string}.onnx`;
  export = path;
}
